### PR TITLE
Minima order condition

### PR DESCRIPTION
**Pull request by araihC**
Minima method to trigger detection update. 
Transition time are identified as the deepest  minima candidate between two good maxima. 
 - Local maxima are identified as maxima provided that:
     1. Two maxima are  separated by at least MIN_PEAK_DISTANCE_MAXIMA 
     2. The intensity is higher than MAXIMA_THRESHOLD_FRACTION than the amplitude span
 -  Local minima are identified as transition candidates provided that  the signal in  the following MINIMA_PERSISTENCE is higher. To implement this the scipy argrelmin funcion has been slightly modified to set the minima order parameter only on one side of the signal acquisition.

### CODE REVIEW

**Review by rgutzen — COMMENTED** [review]
I'm not yet quite sure how the selected minima are exactly defined, but I think the code does not what it is supposed to. For example, the selected minima are not he 'deepest' between two candidate peaks.
For comparison, this is an example of the previous minima detection algorithm using two thresholds:
find_minima_example_threshold

And this is the PR algorithm on the same signal:
find_minima_example_persistance

Can you specify what the desired result should look like?

**Comment by rgutzen** [comment]
> We thus prefer to identify a "wrong" up transition candidate rather then not collecting a "right" one.

I understand that you want to implement a method that is less strict in the minima selection. However, I do not see that this is the case here as, for example, in the above plot there are already several minima that I would consider "right" and that are not collected.

> this algorithm should be used on smooth signals (at which spatial resolution are these recordings measured? maybe a spatial smoothing should be applied). Indeed, we aim at collecting all transition candidates (e.g. the transition of two close consecutive waves) to be further cleaned up by the wave hunt method in stage 04.

Of course, different blocks may work better or worse in certain combinations, but a key aspect of the pipeline design is the modularity, which also means that blocks should be as independent of other blocks and stages as possible, i.e. this method shouldn't strongly rely on any particular filtering before or after, in order to be reasonable or useful.

Therefore, I believe that we can make the detection criteria and the implementation more precise. We can maybe discuss this also in another meeting.

**Comment by araihC** [comment]
Updated Minima transition algorithm. Now it works like this:

- Local maxima are required to be at least 280ms distant (otherwise the higher is selected) and higher than a set threshold [red points]
- the threshold is dynamically detected as 0.4*span of the signal within a 4s time window [black line]
- local minima candidates are required to be at leas 280ms distant (otherwise the lower is selected) and with a persistence of 160ms (next 160ms needs to be higher). [orange points]
- between two maxima only one minimum is accepted: the last one is the selected [green points]

The persistence algorithm needs to be asymmetric (only on one side) to be take into consideration the possibility of flat down-states. 
This is what the output should look like

minima_channel190

I also added a plot of a representative pixel(s) in the pipeline.

**Comment by rgutzen** [comment]
I still see some improvements we can apply to this method, but I think it can also be handled in the master branch as it is running and not interfering with the rest of the pipeline architecture.

**Pull request merged**
